- hosts: localhost
  tasks:
  - firewalld:
      port: 5000/tcp
      state: enabled
      permanent: yes
      immediate: yes

- hosts: slaves
  tasks:
  - firewalld:
      port: 80/tcp
      state: enabled
      permanent: yes
      immediate: yes
